Rack app created using MVC pattern
Kadaverin/RackCodebreakerMVC pull request #1
Opened 2018-07-02 13:36 UTC by Kadaverin

This experiment is complete. 
A "lib" folder is the heart of the application. There is an App class - an entry point to the application, a Router class and a base class for application controllers. The App class wraps the environment variable in the Rack::request and sends it to the router. The router calls the appropriate controllers. The controller renders the views by the action name from the folder with the name of this controller

2018-07-11 16:22 UTC, kirillshevch requested changes

2018-07-11 16:22 UTC, kirillshevch commented on app/controllers/game_controller.rb
> +    request.session['game']
request.session['game'] ||= Codebreaker::Game.new

2018-07-11 16:22 UTC, kirillshevch commented on lib/rackgame/router.rb
> +  # //
???

2018-07-11 16:22 UTC, kirillshevch commented on lib/rackgame/router.rb
> +    rescue Exception => error
rescue Exception => e

2018-08-05 17:55 UTC, hf6cTXNPfyPgOBK6 approved these changes

2019-08-02 06:38 UTC, merged